logging:
  config: classpath:logback-spring.xml
  path: api-log/cn-yiwu-rfy/outerlink


outerlink:
  internal:
    outgoing:
      socket:
        ip: 10.1.1.114
        port: 881
  outgoing-file:
    address: D:\\project_file\\cn-yiwu-rfy\\xml-file\\outgoing\\
  incoming-file:
    address: D:\\project_file\\cn-yiwu-rfy\\xml-file\\incoming\\

cn:
  yiwu:
    rfy:
      station:
        telegraph:
          code: IUH
        tmis:
          code: 32539
        name: 义乌西
      images:
        path: d:/img