package net.pingfang.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-11-15T18:19:19.482+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://ywxhc.service.ws.web.yufei.com/", name = "TCymJcmService")
@XmlSeeAlso({ObjectFactory.class})
public interface TCymJcmService {

    @WebMethod
    @Action(input = "http://ywxhc.service.ws.web.yufei.com/TCymJcmService/saveRequest", output = "http://ywxhc.service.ws.web.yufei.com/TCymJcmService/saveResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://ywxhc.service.ws.web.yufei.com/TCymJcmService/save/Fault/Exception")})
    @RequestWrapper(localName = "save", targetNamespace = "http://ywxhc.service.ws.web.yufei.com/", className = "net.pingfang.webservice.client.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://ywxhc.service.ws.web.yufei.com/", className = "net.pingfang.webservice.client.SaveResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String save(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    net.pingfang.webservice.client.TCymJcm arg1
    ) throws Exception_Exception;

    @WebMethod
    @Action(input = "http://ywxhc.service.ws.web.yufei.com/TCymJcmService/deleteRequest", output = "http://ywxhc.service.ws.web.yufei.com/TCymJcmService/deleteResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://ywxhc.service.ws.web.yufei.com/TCymJcmService/delete/Fault/Exception")})
    @RequestWrapper(localName = "delete", targetNamespace = "http://ywxhc.service.ws.web.yufei.com/", className = "net.pingfang.webservice.client.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://ywxhc.service.ws.web.yufei.com/", className = "net.pingfang.webservice.client.DeleteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int delete(
            @WebParam(name = "arg0", targetNamespace = "")
                    net.pingfang.webservice.client.TCymJcm arg0
    ) throws Exception_Exception;
}
