package net.pingfang.webservice.client;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-11-15T18:19:19.502+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "TCymJcmService", 
                  wsdlLocation = "http://10.137.152.23:8088/services/ywxhc/TCymJcmService?wsdl",
                  targetNamespace = "http://impl.ywxhc.service.ws.web.yufei.com/") 
public class TCymJcmService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ywxhc.service.ws.web.yufei.com/", "TCymJcmService");
    public final static QName TCymJcmServiceImplPort = new QName("http://impl.ywxhc.service.ws.web.yufei.com/", "TCymJcmServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.137.152.23:8088/services/ywxhc/TCymJcmService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TCymJcmService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.137.152.23:8088/services/ywxhc/TCymJcmService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TCymJcmService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TCymJcmService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TCymJcmService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public TCymJcmService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TCymJcmService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TCymJcmService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns TCymJcmService
     */
    @WebEndpoint(name = "TCymJcmServiceImplPort")
    public TCymJcmService getTCymJcmServiceImplPort() {
        return super.getPort(TCymJcmServiceImplPort, TCymJcmService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TCymJcmService
     */
    @WebEndpoint(name = "TCymJcmServiceImplPort")
    public TCymJcmService getTCymJcmServiceImplPort(WebServiceFeature... features) {
        return super.getPort(TCymJcmServiceImplPort, TCymJcmService.class, features);
    }

}
